version: '3.8'

services:
  express:
    build:
      context: ./express-app
    environment:
      NODE_ENV: development
    volumes:
      - ./express-app/dist:/app/dist
    ports:
      - 3001:3001/tcp
  next:
    build:
      context: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000/tcp
  client:
    build:
      context: ./client
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/app
  kasm:
    image: kasmweb/ubuntu-focal-desktop:1.14.0
    environment:
      - VNC_PW=password
    ports:
      - 6901:6901/tcp